### ISSUE TITLE
i know that this is a dumb question but how the hell do i apply a shader to the entire screen in 3d

### ISSUE THREAD

**Issue by 0x177** [Ahopness/GodotRetro#1]
i googled it and spend like an hour looking at tutorials that either applied shader to a single object or the entire screen in 2d not 3d

**Comment by ahopness** [comment]
This is how i apply mine.
- Under your Spatial type node, create a _CanvasLayer_ node - This node will make sure to render your post processing on the right layer
- Then under that, create a _BackBufferCopy_ node - This node will make you able to have more than one post processing shader visible - make sure 'Copy Mode' is set to 'Viewport' and that the size of the node covers the whole screen
- Finnally, under that node, create a _ColorRect_  node - You will apply your post processing shader in this node, first, set the 'Color' property to white, then set the 'Layout' to 'FullRect' to cover the whole screen, then under the 'Material' section, create a new 'ShaderMaterial', in the shader property inside your material, atach your shader of choice. Under 'Shader param' you can edit your shader parameters (duh).

If you want to add more post processing to your game, just repeat the last two steps.

Example images:
(SceneTree)
![image](https://user-images.githubusercontent.com/56614267/178258181-1692ca92-5f7b-4513-9de5-2a3057dd3e6b.png)

(CanvasLayer settings)
![image](https://user-images.githubusercontent.com/56614267/178258232-0b5b2a71-73b1-4a2d-b43b-435fe93ba034.png)

(BackBufferCopy settings)
![image](https://user-images.githubusercontent.com/56614267/178258273-70f769c6-a4ba-4926-a88e-2559c3312b99.png)

(ColorRect settings)
![image](https://user-images.githubusercontent.com/56614267/178258318-d579da3f-a2cc-4f97-bc26-82077929af80.png)

**Comment by ghost** [comment]
thanks
