### ISSUE TITLE
Godot 4 compatibility

### ISSUE THREAD

**Issue by micahlagrange** [Ahopness/GodotRetro#2]
Since 4 is basically almost out, this should have a branch or at least release tag for Godot 4.

**Comment by ahopness** [comment]
fr, gonna start working on that

**Comment by evergoof** [comment]
Any update on it?

**Comment by ahopness** [comment]
> Any update on it?

[I finished it ](https://github.com/Ahopness/GodotRetro/tree/4.x) , just didn't announced anything bc there's a bugs with model importing on my pc that prevents me from making sure everything looks as it should on gd4
