### ISSUE TITLE
iTime don't works

### ISSUE THREAD

**Issue by therabug** [Ahopness/GodotRetro#5]
Just it moves according to screen movement not time. (NTSC.gdshader)

**Comment by ahopness** [comment]
which version of godot are u on?? and is the low processor mode setting turned on in your project?

**Comment by therabug** [comment]
> which version of godot are u on?? and is the low processor mode setting turned on in your project?

sorry for late reply godot version 4.2 and low processor mode is off

**Comment by ahopness** [comment]
took 3 years but NTSC shader is now fixed btw (sry)

**Comment by therabug** [comment]
> took 3 years but NTSC shader is now fixed btw (sry)

LMAO attention to the dedication lol
